matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2
addons:
  apt:
    packages:
      - fakeroot
      - rpm
language: java
jdk: openjdk11
script: ./ganttproject-builder/build-travis.sh
branches:
  only:
    - master
    - /^tkt-.*$/
    - /^prj-.*$/
